{{- if .Values.ingress.enabled }}
{{- $extraHosts := default (list) .Values.ingress.extraHosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  labels:
    app: n8n
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
    {{- if .Values.ingress.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "{{ .Values.ingress.basicAuth.secretName }}"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - N8N"
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
    {{- range $extraHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
    {{- if .Values.ingress.allowLoadBalancerHostname }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
  {{- if and .Values.ingress.tls.enabled (or .Values.ingress.host (gt (len $extraHosts) 0)) }}
  # TLS configuration
  # - For BYO certificates: secretName points to Terraform-created secret
  # - For Let's Encrypt: secretName is auto-created by cert-manager (requires cert-manager.io/cluster-issuer annotation above)
  tls:
    - hosts:
        {{- if .Values.ingress.host }}
        - {{ .Values.ingress.host }}
        {{- end }}
        {{- range $extraHosts }}
        {{- if . }}
        - {{ . }}
        {{- end }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
