apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels: { app: n8n }
spec:
  type: {{ .Values.service.type }}
  selector: { app: n8n }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5678
