image:
  repository: docker.n8n.io/n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  host: n8n.example.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/ssl-prefer-server-ciphers: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
    # For Let's Encrypt, add:
    # cert-manager.io/cluster-issuer: "letsencrypt-production"
  extraHosts: []
  allowLoadBalancerHostname: true  # Respond to requests that use the raw ELB hostname
  tls:
    # Set to false for HTTP-only (no TLS)
    # Set to true when using BYO certificate or Let's Encrypt
    enabled: true
    # Name of the Kubernetes TLS secret
    # - For BYO: secret created by Terraform with user-provided cert
    # - For Let's Encrypt: secret created by cert-manager automatically
    secretName: n8n-tls
  basicAuth:
    # Enable basic authentication for ingress
    enabled: false
    # Name of the Kubernetes Secret containing auth credentials (htpasswd format)
    # This secret is created by setup.py in Phase 4 when basic auth is enabled
    secretName: n8n-basic-auth

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Non-sensitive environment variables
# Note: When deployed via Terraform, many of these values are overridden
# based on terraform.tfvars configuration (host, protocol, timezone, etc.)
env:
  N8N_HOST: "n8n.example.com"
  N8N_PROTOCOL: "https"  # Set to "http" when tls.enabled=false
  N8N_PORT: "5678"
  N8N_RUNNERS_ENABLED: "true"
  GENERIC_TIMEZONE: "America/Bahia"
  TZ: "America/Bahia"
  WEBHOOK_URL: "https://n8n.example.com/"
  N8N_PROXY_HOPS: "1"

# Sensitive environment variables (templated into a Kubernetes Secret)
# Note: When deployed via Terraform, N8N_ENCRYPTION_KEY is automatically
# set from AWS SSM Parameter Store (generated or user-provided)
envSecrets: {}

# Database configuration
# Note: When deployed via Terraform with PostgreSQL, these values are
# automatically set from terraform outputs (RDS endpoint, credentials, etc.)
database:
  # Type of database: sqlite (default) or postgresql
  type: sqlite
  # PostgreSQL configuration (only used when type = postgresql)
  postgresql:
    host: ""
    port: 5432
    database: "n8n"
    user: ""
    password: ""

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

# PodDisruptionBudget - only enable when running multiple replicas
# to avoid blocking node drains with single replica
pdb:
  enabled: false
  minAvailable: 1
