image:
  repository: docker.n8n.io/n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  host: n8n.example.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # For Let's Encrypt, add:
    # cert-manager.io/cluster-issuer: "letsencrypt-production"
  tls:
    # Set to false for HTTP-only (no TLS)
    # Set to true when using BYO certificate or Let's Encrypt
    enabled: true
    # Name of the Kubernetes TLS secret
    # - For BYO: secret created by Terraform with user-provided cert
    # - For Let's Encrypt: secret created by cert-manager automatically
    secretName: n8n-tls

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Non-sensitive environment variables
# Note: When deployed via Terraform, many of these values are overridden
# based on terraform.tfvars configuration (host, protocol, timezone, etc.)
env:
  N8N_HOST: "n8n.example.com"
  N8N_PROTOCOL: "https"  # Set to "http" when tls.enabled=false
  N8N_PORT: "5678"
  N8N_RUNNERS_ENABLED: "true"
  GENERIC_TIMEZONE: "America/Bahia"
  TZ: "America/Bahia"
  WEBHOOK_URL: "https://n8n.example.com/"
  N8N_PROXY_HOPS: "1"

# Sensitive environment variables (templated into a Kubernetes Secret)
# Note: When deployed via Terraform, N8N_ENCRYPTION_KEY is automatically
# set from AWS SSM Parameter Store (generated or user-provided)
envSecrets: {}

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

# PodDisruptionBudget - only enable when running multiple replicas
# to avoid blocking node drains with single replica
pdb:
  enabled: false
  minAvailable: 1
